/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BookingSystem.java
 *
 * Created on Jun 17, 2022, 6:48:48 PM
 */
package bsicinematiket;

import javax.swing.JOptionPane;



/**
 *
 * @author PC
 */
public class BookingSystem extends javax.swing.JFrame {
    int reguler,harga,beli,total,bayar,kembali,reguler2;
 
    /** Creates new form BookingSystem */
    public BookingSystem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        txttotal = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txtnomorkrs = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfilm = new javax.swing.JComboBox();
        txtjadwal = new javax.swing.JComboBox();
        txtjam = new javax.swing.JComboBox();
        rbreguler = new javax.swing.JRadioButton();
        txtharga = new javax.swing.JTextField();
        rbreguler2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        input = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        btcetak = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 5));

        txttotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        txtjumlah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahKeyReleased(evt);
            }
        });

        txtnomorkrs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel11.setFont(new java.awt.Font("Bell MT", 0, 14));
        jLabel11.setText("Uang Kembali");

        jLabel10.setFont(new java.awt.Font("Bell MT", 0, 14));
        jLabel10.setText("Uang Bayar");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booking System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Showcard Gothic", 0, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14));
        jLabel2.setText("Movie");

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14));
        jLabel3.setText("Jadwal");

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14));
        jLabel4.setText("Jam");

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 14));
        jLabel5.setText("Jenis");

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 14));
        jLabel6.setText("Harga");

        txtfilm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Spider-Man No Way Home", "Doctor Strange In The Multiverse OF Madness", "Thor Love and Thunder", "Top Gun Maverick", " " }));
        txtfilm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilmActionPerformed(evt);
            }
        });

        txtjadwal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Rabu 1 Juni 2022", "Kamis 2 Juni 2022", "Jumat 3 Juni 2022", "Sabtu 4 Juni 2022", "Minggu 5 Juni 2022", "Senin 6 Juni 2022", " " }));
        txtjadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjadwalActionPerformed(evt);
            }
        });

        txtjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "12.00", "14.00", "16.00", "20.00", " " }));
        txtjam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjamActionPerformed(evt);
            }
        });

        rbreguler.setFont(new java.awt.Font("Arial", 0, 14));
        rbreguler.setText("Reguler 2D");
        rbreguler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbreguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbregulerActionPerformed(evt);
            }
        });

        rbreguler2.setFont(new java.awt.Font("Arial", 0, 14));
        rbreguler2.setText("Netflix And Chill");
        rbreguler2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbreguler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbreguler2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbreguler)
                                .addGap(18, 18, 18)
                                .addComponent(rbreguler2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtjam, 0, 645, Short.MAX_VALUE)
                                .addComponent(txtfilm, 0, 645, Short.MAX_VALUE)
                                .addComponent(txtjadwal, 0, 645, Short.MAX_VALUE)))
                        .addContainerGap(20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtjadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbreguler)
                    .addComponent(rbreguler2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 14));
        jLabel7.setText("Nomor Kursi");

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 14));
        jLabel8.setText("Jumlah Beli");

        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 14));
        jLabel9.setText("Total Bayar");

        txtbayar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
        });

        txtkembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtarea.setBackground(new java.awt.Color(102, 255, 102));
        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Century Schoolbook", 0, 14));
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        input.setBackground(new java.awt.Color(102, 102, 102));
        input.setText("Reset");
        input.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        input.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        keluar.setBackground(new java.awt.Color(255, 0, 51));
        keluar.setText("Keluar");
        keluar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        btcetak.setBackground(new java.awt.Color(102, 102, 255));
        btcetak.setText("Print");
        btcetak.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        btcetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcetakActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/tz7Md.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 5));
        jPanel3.setForeground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36));
        jLabel1.setText("BSI CINEMA TICKET");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(713, 713, 713)
                .addComponent(jLabel1)
                .addContainerGap(742, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setText("Movie Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btcetak, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(13, 13, 13)
                                        .addComponent(txtnomorkrs, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(25, 25, 25)
                                        .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(9, 9, 9)
                                            .addComponent(txtkembalian))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(20, 20, 20)
                                            .addComponent(txtbayar))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(21, 21, 21)
                                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(txtnomorkrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjadwalActionPerformed
// TODO add your handling code here:
    // membuat kondisi untuk menentukan harga sesuai film
if(txtfilm.getSelectedItem().equals("Pilih Jadwal")){
    buttonGroup1.clearSelection();
    txtharga.setText("");
}
else if(txtjadwal.getSelectedItem().equals("Rabu 1 Juni 2022")){
   reguler=25000;
   reguler2=50000;
}
else if(txtjadwal.getSelectedItem().equals("Kamis 2 Juni 2022")){
   reguler=25000;
    reguler2=50000;
}
else if(txtjadwal.getSelectedItem().equals("Jumat 3 Juni 2022")){
   reguler=30000; 
    reguler2=60000;
}
else if(txtjadwal.getSelectedItem().equals("Sabtu 4 Juni 2022")){
   reguler=35000;
    reguler2=60000;
}
else if(txtjadwal.getSelectedItem().equals("Minggu 5 Juni 2022")){
   reguler=40000;
    reguler2=80000;
}
else if(txtjadwal.getSelectedItem().equals("Senin 6 Juni 2022")){
    reguler=25000;
    reguler2=50000;
}
}//GEN-LAST:event_txtjadwalActionPerformed

private void txtjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjamActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtjamActionPerformed

private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txttotalActionPerformed

private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
// TODO add your handling code here:
    buttonGroup1.clearSelection();
    txtharga.setText("");
    txtjadwal.setSelectedItem("Pilih Jadwal");
    txtnomorkrs.setText("");
    txttotal.setText("");
    txtjumlah.setText("");
    txtbayar.setText("");
    txtkembalian.setText("");
}//GEN-LAST:event_inputActionPerformed

private void txtfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilmActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtfilmActionPerformed

private void rbregulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbregulerActionPerformed
// TODO add your handling code here:
    if(rbreguler.isSelected()){
        txtharga.setText(String.valueOf(reguler));
    }
}//GEN-LAST:event_rbregulerActionPerformed

private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
// TODO add your handling code here:
    beli=Integer.parseInt(txtjumlah.getText());
    harga=Integer.parseInt(txtharga.getText());
    total=bayar*harga;
    txttotal.setText(String.valueOf(total));
}//GEN-LAST:event_txtjumlahActionPerformed

private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
// TODO add your handling code here:
    bayar=Integer.parseInt(txtbayar.getText());
    kembali=Integer.parseInt(txttotal.getText());
    total=bayar-kembali;
    txtkembalian.setText(String.valueOf(total));
}//GEN-LAST:event_txtbayarActionPerformed

private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
// TODO add your handling code here:
    int answer=JOptionPane.showConfirmDialog(null,"Are you Sure?","EXIT",JOptionPane.OK_OPTION);
    if (answer==JOptionPane.OK_OPTION){
        dispose();
    }
}//GEN-LAST:event_keluarActionPerformed

private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
// TODO add your handling code here:
    int a,b,c;
    a=Integer.valueOf(txtbayar.getText());
    b=Integer.valueOf(txttotal.getText());
    c=a-b;
    txtkembalian.setText(""+c);
}//GEN-LAST:event_txtbayarKeyReleased

private void btcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcetakActionPerformed
// TODO add your handling code here:
   btcetak.setText((String)txtjadwal.getSelectedItem());
   txtarea.setText(
           "Nomor Kursi  :"+txtnomorkrs.getText()+"\n"+
           "Jumlah Beli  :"+txtjumlah.getText()+"\n"+
           "Total Bayar  :"+txttotal.getText()+"\n"+
           "Uang Bayar  :"+txtbayar.getText()+"\n"+
           "Uang Kembalian  :"+txtkembalian.getText()+"\n"+
                      "TERIMA KASIH");
    
}//GEN-LAST:event_btcetakActionPerformed

private void txtjumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyReleased
// TODO add your handling code here:
     int a,b,c;
    a=Integer.valueOf(txtharga.getText());
    b=Integer.valueOf(txtjumlah.getText());
    c=a*b;
    txttotal.setText(""+c);
}//GEN-LAST:event_txtjumlahKeyReleased

private void rbreguler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbreguler2ActionPerformed
// TODO add your handling code here:
    if(rbreguler2.isSelected()){
        txtharga.setText(String.valueOf(reguler2));
    }
}//GEN-LAST:event_rbreguler2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
      new Showing().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BookingSystem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcetak;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton input;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JRadioButton rbreguler;
    private javax.swing.JRadioButton rbreguler2;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JComboBox txtfilm;
    private javax.swing.JTextField txtharga;
    private javax.swing.JComboBox txtjadwal;
    private javax.swing.JComboBox txtjam;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtnomorkrs;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
